services:
  devcontainer:
    # added the platform flag to override any local settings since this image is only compatible with linux/amd64.
    platform: linux/amd64
    build:
      context: .
      args:
        REPO_NAME: rytermedia-com
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/rytermedia-com:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_infrastructure_venv:/workspaces/rytermedia-com/infrastructure/.venv
      # Break out the pnpm store folder as a separate docker volume for better performance on Windows hosts
      - pnpm_store:/workspaces/rytermedia-com/.pnpm-store
      # And node_modules
      - node_modules:/workspaces/rytermedia-com/node_modules
    command: sleep infinity
    ports:
      - "49932:2222"
    environment:
      - AWS_PROFILE=artifacts
      - AWS_DEFAULT_REGION=us-east-1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BEADS_DIR=/workspaces/rytermedia-com/.claude/.beads
      - BEADS_DOLT_SERVER_HOST=beads-dolt # this is on the docker compose network. We don't want to publish the server port because then the local machine would have a bunch of conflicts with multiple devcontainers running
      - BEADS_DOLT_SERVER_PORT=3306
      - BEADS_DOLT_SERVER_DATABASE=beads_work
      - BEADS_DOLT_SERVER=beads-dolt # for some weird reason, unless we specify both of these envvars it doesn't seem to reliably work
      - BEADS_DOLT_PORT=3306


  beads-dolt:
    image: dolthub/dolt-sql-server:1.83.0 # no explicit reason for this version, just pinning for best practice
    volumes:
      - beads_dolt_data:/var/lib/dolt
    environment:
      - DOLT_ROOT_HOST=%
      - DOLT_DATABASE=beads_work


volumes:
  beads_dolt_data: {}
  python_infrastructure_venv: {}
  pnpm_store: {}
  node_modules: {}
