[project]
name = "infrastructure"
version = "0.1.0"
description = "Infrastructure to support frontend and backend"

readme = "README.md"
requires-python = ">=3.13.2"

dependencies = [
    # Specific to this project

    # Managed by upstream template
    "pyright>=1.1.409",
    "ty>=0.0.40",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-randomly>=4.1.0",
    "pulumi>=3.234.0",
    "pulumi-aws>=7.28.0",
    "pulumi-aws-native>=1.63.0",
    "pulumi-command>=1.2.1",
    "ephemeral-pulumi-deploy>=0.0.6",
    "lab-auto-pulumi>=0.2.0",
    "boto3>=1.42.92",
    "boto3-stubs[all]>=1.42.92",
]

[tool.uv]
package = true
